version: '3'
services:
  app:
    build: ./app
    container_name: php_app
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - my_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
volumes:
  my_data:
